# Generated by Django 3.2.3 on 2021-05-22 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produce',
            new_name='Product',
        ),
    ]
