# Generated by Django 3.0.8 on 2021-06-22 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20210622_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 22, 31, 50, 606773)),
        ),
        migrations.AlterField(
            model_name='brand',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 22, 31, 50, 606773)),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 22, 31, 50, 574287)),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 22, 31, 50, 574287)),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 22, 31, 50, 608770)),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 22, 31, 50, 608770)),
        ),
        migrations.AlterField(
            model_name='productdepartment',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 22, 31, 50, 605775)),
        ),
        migrations.AlterField(
            model_name='productdepartment',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 22, 31, 50, 605775)),
        ),
        migrations.AlterField(
            model_name='productkind',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 22, 31, 50, 607770)),
        ),
        migrations.AlterField(
            model_name='productkind',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 22, 31, 50, 607770)),
        ),
        migrations.AlterField(
            model_name='productoverview',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 22, 31, 50, 607770)),
        ),
        migrations.AlterField(
            model_name='productoverview',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 22, 31, 50, 607770)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 22, 31, 50, 606773)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='post_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 22, 31, 50, 606773)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 22, 31, 50, 606773)),
        ),
        migrations.AlterField(
            model_name='sellperiod',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 22, 31, 50, 605775)),
        ),
        migrations.AlterField(
            model_name='sellperiod',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 22, 31, 50, 605775)),
        ),
        migrations.AlterField(
            model_name='size',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 22, 31, 50, 607770)),
        ),
        migrations.AlterField(
            model_name='size',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 22, 31, 50, 607770)),
        ),
        migrations.AlterField(
            model_name='sizedetail',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 22, 31, 50, 607770)),
        ),
        migrations.AlterField(
            model_name='sizedetail',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 22, 31, 50, 607770)),
        ),
        migrations.AlterField(
            model_name='store',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 22, 31, 50, 606773)),
        ),
        migrations.AlterField(
            model_name='store',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 22, 31, 50, 606773)),
        ),
    ]
