# Generated by Django 3.0.8 on 2021-08-10 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='', max_length=250)),
                ('store_id', models.IntegerField(default=0)),
                ('create_datetime', models.DateTimeField(default=datetime.datetime(2021, 8, 10, 20, 27, 38, 825112))),
                ('update_datetime', models.DateTimeField(default=datetime.datetime(2021, 8, 10, 20, 27, 38, 825112))),
                ('visibility', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=250)),
                ('product_department_id', models.IntegerField(default=0)),
                ('product_kind_id', models.IntegerField(default=0)),
                ('brand_id', models.IntegerField(blank=True, null=True)),
                ('store_id', models.IntegerField(default=0)),
                ('ASIN_code', models.CharField(default='', max_length=100)),
                ('display_flag', models.BooleanField(default=False)),
                ('create_datetime', models.DateTimeField(default=datetime.datetime(2021, 8, 10, 20, 27, 38, 790208))),
                ('update_datetime', models.DateTimeField(default=datetime.datetime(2021, 8, 10, 20, 27, 38, 790208))),
                ('visibility', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_color', models.CharField(default=0, max_length=250)),
                ('product_figure_path', models.TextField(default='')),
                ('store_id', models.IntegerField(default=0)),
                ('create_datetime', models.DateTimeField(default=datetime.datetime(2021, 8, 10, 20, 27, 38, 826110))),
                ('update_datetime', models.DateTimeField(default=datetime.datetime(2021, 8, 10, 20, 27, 38, 826110))),
                ('visibility', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_department_name', models.CharField(default='', max_length=250)),
                ('create_datetime', models.DateTimeField(default=datetime.datetime(2021, 8, 10, 20, 27, 38, 824088))),
                ('update_datetime', models.DateTimeField(default=datetime.datetime(2021, 8, 10, 20, 27, 38, 824088))),
                ('visibility', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_kind_name', models.CharField(default='', max_length=250)),
                ('store_id', models.IntegerField(default=0)),
                ('create_datetime', models.DateTimeField(default=datetime.datetime(2021, 8, 10, 20, 27, 38, 825112))),
                ('update_datetime', models.DateTimeField(default=datetime.datetime(2021, 8, 10, 20, 27, 38, 825112))),
                ('visibility', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOverView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('product_id', models.IntegerField(default=0)),
                ('store_id', models.IntegerField(default=0)),
                ('create_datetime', models.DateTimeField(default=datetime.datetime(2021, 8, 10, 20, 27, 38, 826110))),
                ('update_datetime', models.DateTimeField(default=datetime.datetime(2021, 8, 10, 20, 27, 38, 826110))),
                ('visibility', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=0)),
                ('evaluation', models.IntegerField(default=0)),
                ('comment', models.TextField(default='')),
                ('user_id', models.IntegerField(default=0)),
                ('post_datetime', models.DateTimeField(default=datetime.datetime(2021, 8, 10, 20, 27, 38, 824088))),
                ('create_datetime', models.DateTimeField(default=datetime.datetime(2021, 8, 10, 20, 27, 38, 824088))),
                ('update_datetime', models.DateTimeField(default=datetime.datetime(2021, 8, 10, 20, 27, 38, 824088))),
                ('visibility', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(default='')),
                ('end_datetime', models.DateTimeField(default='')),
                ('product_id', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('store_id', models.IntegerField(default=0)),
                ('create_datetime', models.DateTimeField(default=datetime.datetime(2021, 8, 10, 20, 27, 38, 824088))),
                ('update_datetime', models.DateTimeField(default=datetime.datetime(2021, 8, 10, 20, 27, 38, 824088))),
                ('visibility', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(default='', max_length=250)),
                ('product_kind_id', models.IntegerField(default=0)),
                ('store_id', models.IntegerField(default=0)),
                ('create_datetime', models.DateTimeField(default=datetime.datetime(2021, 8, 10, 20, 27, 38, 826110))),
                ('update_datetime', models.DateTimeField(default=datetime.datetime(2021, 8, 10, 20, 27, 38, 826110))),
                ('visibility', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SizeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_detail_name', models.CharField(default='', max_length=250)),
                ('store_id', models.IntegerField(default=0)),
                ('create_datetime', models.DateTimeField(default=datetime.datetime(2021, 8, 10, 20, 27, 38, 826110))),
                ('update_datetime', models.DateTimeField(default=datetime.datetime(2021, 8, 10, 20, 27, 38, 826110))),
                ('visibility', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='', max_length=250)),
                ('directly_managed_flag', models.BooleanField(default=False)),
                ('email', models.TextField(default='')),
                ('password', models.CharField(default='', max_length=20)),
                ('create_datetime', models.DateTimeField(default=datetime.datetime(2021, 8, 10, 20, 27, 38, 825112))),
                ('update_datetime', models.DateTimeField(default=datetime.datetime(2021, 8, 10, 20, 27, 38, 825112))),
                ('visibility', models.BooleanField(default=True)),
            ],
        ),
    ]
