# Generated by Django 3.0.8 on 2021-06-23 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsite', '0006_auto_20210622_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 39, 4, 920473)),
        ),
        migrations.AlterField(
            model_name='brand',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 39, 4, 920473)),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 39, 4, 887566)),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 39, 4, 887566)),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 39, 4, 921471)),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 39, 4, 921471)),
        ),
        migrations.AlterField(
            model_name='productdepartment',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 39, 4, 918480)),
        ),
        migrations.AlterField(
            model_name='productdepartment',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 39, 4, 918480)),
        ),
        migrations.AlterField(
            model_name='productkind',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 39, 4, 920473)),
        ),
        migrations.AlterField(
            model_name='productkind',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 39, 4, 920473)),
        ),
        migrations.AlterField(
            model_name='productoverview',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 39, 4, 921471)),
        ),
        migrations.AlterField(
            model_name='productoverview',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 39, 4, 921471)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 39, 4, 919476)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='post_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 39, 4, 919476)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 39, 4, 919476)),
        ),
        migrations.AlterField(
            model_name='sellperiod',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 39, 4, 919476)),
        ),
        migrations.AlterField(
            model_name='sellperiod',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 39, 4, 919476)),
        ),
        migrations.AlterField(
            model_name='size',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 39, 4, 920473)),
        ),
        migrations.AlterField(
            model_name='size',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 39, 4, 921471)),
        ),
        migrations.AlterField(
            model_name='sizedetail',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 39, 4, 921471)),
        ),
        migrations.AlterField(
            model_name='sizedetail',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 39, 4, 921471)),
        ),
        migrations.AlterField(
            model_name='store',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 39, 4, 920473)),
        ),
        migrations.AlterField(
            model_name='store',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 39, 4, 920473)),
        ),
    ]
