# Generated by Django 3.0.8 on 2021-06-23 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsite', '0008_auto_20210623_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='brand',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 51, 31, 370043)),
        ),
        migrations.AlterField(
            model_name='brand',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 51, 31, 370043)),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 51, 31, 337099)),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 51, 31, 337099)),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 51, 31, 372035)),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 51, 31, 372035)),
        ),
        migrations.AlterField(
            model_name='productdepartment',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 51, 31, 369043)),
        ),
        migrations.AlterField(
            model_name='productdepartment',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 51, 31, 369043)),
        ),
        migrations.AlterField(
            model_name='productkind',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 51, 31, 371036)),
        ),
        migrations.AlterField(
            model_name='productkind',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 51, 31, 371036)),
        ),
        migrations.AlterField(
            model_name='productoverview',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 51, 31, 371036)),
        ),
        migrations.AlterField(
            model_name='productoverview',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 51, 31, 371036)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 51, 31, 370043)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='post_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 51, 31, 370043)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 51, 31, 370043)),
        ),
        migrations.AlterField(
            model_name='sellperiod',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 51, 31, 369043)),
        ),
        migrations.AlterField(
            model_name='sellperiod',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 51, 31, 369043)),
        ),
        migrations.AlterField(
            model_name='size',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 51, 31, 371036)),
        ),
        migrations.AlterField(
            model_name='size',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 51, 31, 371036)),
        ),
        migrations.AlterField(
            model_name='sizedetail',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 51, 31, 371036)),
        ),
        migrations.AlterField(
            model_name='sizedetail',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 51, 31, 371036)),
        ),
        migrations.AlterField(
            model_name='store',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 51, 31, 370043)),
        ),
        migrations.AlterField(
            model_name='store',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 15, 51, 31, 370043)),
        ),
    ]
